# Generated by Django 2.2.16 on 2022-06-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220610_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-name',)},
        ),
    ]
